# Generated by Django 5.0.1 on 2024-03-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
