# Generated by Django 5.0.1 on 2024-03-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='shop/test', upload_to='.images/'),
        ),
    ]
