# Generated by Django 5.0.1 on 2024-04-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_productbid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductBid',
        ),
    ]
