# Generated by Django 5.0.1 on 2024-04-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_productbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highestbid',
            field=models.IntegerField(default=0),
        ),
    ]
